# Default Kibana configuration from kibana-docker.

server.name: kibana_docker_schoolproject
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
